# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaovitorwolfart/Dropbox/DESAFIO HACKATHON/novas-telas/pacientes.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1211, 874)
        MainWindow.setMinimumSize(QtCore.QSize(1211, 874))
        MainWindow.setMaximumSize(QtCore.QSize(1211, 874))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_id_user = QtWidgets.QLabel(self.centralwidget)
        self.lbl_id_user.setGeometry(QtCore.QRect(1080, 30, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_id_user.setFont(font)
        self.lbl_id_user.setStyleSheet("color: rgb(62, 132, 238);")
        self.lbl_id_user.setText("")
        self.lbl_id_user.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_id_user.setObjectName("lbl_id_user")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 921, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.TabelaPacientes = QtWidgets.QTableWidget(self.centralwidget)
        self.TabelaPacientes.setEnabled(True)
        self.TabelaPacientes.setGeometry(QtCore.QRect(40, 90, 961, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaPacientes.sizePolicy().hasHeightForWidth())
        self.TabelaPacientes.setSizePolicy(sizePolicy)
        self.TabelaPacientes.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TabelaPacientes.setFont(font)
        self.TabelaPacientes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaPacientes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(138, 226, 52);\n"
"color: rgb(32, 74, 135);")
        self.TabelaPacientes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaPacientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaPacientes.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaPacientes.setObjectName("TabelaPacientes")
        self.TabelaPacientes.setColumnCount(4)
        self.TabelaPacientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPacientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPacientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPacientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPacientes.setHorizontalHeaderItem(3, item)
        self.TabelaPacientes.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaPacientes.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaPacientes.horizontalHeader().setStretchLastSection(True)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(960, 650, 231, 211))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/home/joaovitorwolfart/Dropbox/DESAFIO HACKATHON/novas-telas/../IMAGENS/pngwing.com (1).png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Seleção de pacientes"))
        self.label_4.setText(_translate("MainWindow", "Dê um duplo clique para selecionar o paciente"))
        self.TabelaPacientes.setSortingEnabled(False)
        item = self.TabelaPacientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.TabelaPacientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Prontuário"))
        item = self.TabelaPacientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nome do Paciente"))
        item = self.TabelaPacientes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
