# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaovitorwolfart/Dropbox/DESAFIO HACKATHON/novas-telas/tutorial_braden.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1050, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1050, 740))
        self.frame.setMaximumSize(QtCore.QSize(1050, 740))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 991, 671))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tutorial Escala de Braden"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:22pt; color:#4e9a06;\">Escala de Braden</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    É um recurso de avaliação do risco de desenvolvimento de lesão por pressão é fundamental para determinar as estratégias adequadas para cada paciente.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    Você já ouviu falar sobre a Escala de Braden? Desenvolvida pela enfermeira norte-americana Barbara Braden, trata-se de um instrumento de avaliação do risco de desenvolvimento de lesão por pressão em pacientes. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    De acordo com os resultados desta avaliação, profissionais de saúde conseguem identificar os pacientes em risco e aplicar medidas preventivas para evitar o desenvolvimento das lesões por pressão.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    Embora existam outros recursos disponíveis, como as escalas de Norton e Waterlow, a de Braden é a mais conhecida e utilizada no Brasil.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:14pt;\"><br /></span><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#009c14;\">Como a Escala de Braden funciona? </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">A escala de Braden utiliza seis parâmetros para avaliação do paciente. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">Confira a descrição de cada um deles: </span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Percepção sensorial:</span><span style=\" font-size:16px;\"> relacionada ao desconforto, habilidade de responder à pressão;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Umidade: </span><span style=\" font-size:16px;\">nível ao qual a pele é exposta à umidade; </span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Atividade: </span><span style=\" font-size:16px;\">grau de atividade física; </span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Mobilidade:</span><span style=\" font-size:16px;\"> capacidade de alterar a posição do corpo;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Nutrição: </span><span style=\" font-size:16px;\">padrão de alimentação </span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Fricção e Cisalhamento:</span><span style=\" font-size:16px;\"> Fricção é quando a pele se move contra a superfície de suporte; Cisalhamento a pele, tecidos profundos e a proeminência óssea deslizam uma sobre a outra </span></li></ol>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; font-family:\'Ubuntu\'; font-size:14pt; background-color:#ffffff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    Essas características são avaliadas e pontuadas de 1 a 4, sendo que quanto menor é a pontuação maior o risco do paciente. Todos os fatores somados devem resultar em um número entre 6 e 23 e, partir deste resultado, o enfermeiro poderá classificar o risco dos pacientes e implementar as estratégias.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    Vale lembrar que quanto maior é a pontuação, menor é o risco. Ou seja, um paciente cuja soma da avaliação totalizar 23, não apresenta risco de desenvolver LP. Já quem apresentar a pontuação mínima, 6, é classificado como paciente com risco severo de lesão por pressão. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:14pt;\"><br /></span><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#009c14;\">Como é realizada a classificação de risco de acordo com o resultado obtido na Escala de Braden? </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    A pontuação obtida na Escala de Braden vai direcionar as estratégias preventivas a serem adotadas pelo profissional de saúde. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    Abaixo seguem algumas medidas preventivas que devem ser implementadas de acordo com o risco identificado: </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Risco baixo (15 a 18 pontos): </span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Avaliação da pele sobre proeminências ósseas e abaixo de dispositivos médicos;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Hidratação da pele;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Gerenciamento da umidade;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Acompanhamento nutricional;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Observar alterações na condição clínica e no risco do paciente.</span></li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\"><br /></p>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Risco moderado (13 a 14 pontos): </span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Avaliação da pele sobre proeminências ósseas e abaixo de dispositivos médicos;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Hidratação da pele;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Reposicionamento do paciente seguindo o cronograma estabelecido;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Uso de uma superfície de suporte adequada (colchão viscoelástico, pneumático)</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Aplicação do Mepilex® Border Sacrum, Mepilex® Border Heel e Mepilex® Border Flex nas proeminências ósseas em risco;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Elevação dos calcâneos associado a cobertura para prevenção;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Gerenciamento da umidade;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Acompanhamento nutricional;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Observar alterações na condição clínica e no risco do paciente.</span></li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\"><br /></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Risco alto (10 a 12 pontos):</span><span style=\" font-size:16px;\"> </span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Avaliação da pele sobre proeminências ósseas e abaixo de dispositivos médicos;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Hidratação da pele;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Reposicionamento do paciente seguindo o cronograma estabelecido;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Uso de uma superfície de suporte adequada (colchão viscoelástico, pneumático)</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Aplicação do Mepilex® Border Sacrum, Mepilex® Border Heel e Mepilex® Border Flex nas proeminências ósseas em risco;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Elevação dos calcâneos associado a cobertura para prevenção;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Gerenciamento da umidade;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Acompanhamento nutricional;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Observar alterações na condição clínica e no risco do paciente.</span></li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\"><br /></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:696;\">Risco muito alto (≤ 9 pontos): </span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Avaliação da pele sobre proeminências ósseas e abaixo de dispositivos médicos;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Hidratação da pele;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Reposicionamento do paciente seguindo o cronograma estabelecido;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Uso de uma superfície de suporte adequada (colchão viscoelástico, pneumático)</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Aplicação do Mepilex® Border Sacrum, Mepilex® Border Heel e Mepilex® Border Flex nas proeminências ósseas em risco;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Elevação dos calcâneos associado a cobertura para prevenção;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Gerenciamento da umidade;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Acompanhamento nutricional;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Observar alterações na condição clínica e no risco do paciente.</span></li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; font-weight:696; color:#ef2929;\">Qual a importância de evitar lesões por pressão? </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\">    A lesão por pressão, também conhecida como úlcera por pressão, ocorre quando a pele é pressionada entre o osso do corpo e uma superfície externa, como por exemplo, uma cama ou uma cadeira, ou quando a pele e os tecidos profundos sofrem ação de forças como fricção e cisalhamento. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:20pt; font-weight:600; text-decoration: underline; color:#55555a;\">Alguns cuidados podem evitar esse tipo de lesão. </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:20pt; font-weight:600; text-decoration: underline; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px; font-weight:400;\">Reposicione o paciente, pelo menos, a cada duas horas;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Evite deslizar ou arrastar seu corpo na cama ou poltrona. </span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Uma dieta saudável também é muito importante;</span></li>\n"
"<li style=\" font-family:\'MHCDin,Arial,Helvetica Neue,Helvetica,Roboto,sans-serif\'; font-size:14pt; color:#55555a;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Aplique as coberturas Mepilex® Border Sacrum, Mepilex® Border Heel e Mepilex® Border Flex nas proeminências ósseas em risco de desenvolver Lesão por Pressão.</span></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:14pt;\"><br /></span></p></body></html>"))
